{% set name = "beetlesafari" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/beetlesafari-{{ version }}.tar.gz
  sha256: 6fdb3fbf9e4e32eab3065bc4c53232737c31a9ec064e8e0255ff14532e6314fa

build:
  script_env:
    - QT_QPA_PLATFORM=offscreen
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - cachetools
    - dask-core
    - magicgui
    - napari
    - napari-pyclesperanto-assistant
    - napari-tools-menu
    - numpy
    - pyclesperanto-prototype
    - pyopencl
    - python >={{ python_min }}
    - requests
    - scikit-image
    - toolz

test:
  imports:
    - beetlesafari
  commands:
    - pip list
    - pip check
  requires:
    - oclgrind
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/haesleinhuepf/beetlesafari
  summary: A napari plugin for loading and working with light sheet imaging data of developing embryos acquired using ClearControl, e.g. _Tribolium castaneum_.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - haesleinhuepf
    - goanpeca
    - jaimergp
